extends Node
#相当于是一个全局的数据访问文档，只读
var ItemRference={
    "木材":{
        "ID":1,                                 #ID，代表物品编号，也可以认为是另一种代号
        "Type":"Resource",                      #类型，便于区分
        "Weight":1,                             #单个物品重量
        "Usable":false,                         #是否可以直接在背包中使用
        "Price":1,                              #单价（出售）
        "Description":"一小堆木材，常见的建筑材料。" 
        },
    "9mm子弹":{
        "ID":11,
        "Type":"Bullet",
        "Weight":0.01,
        "Usable":false,
        "Price":0.5,
        "Description":"常用于手枪。"
       },
    "雷明顿16号弹":{
        "ID":12,
        "Type":"Bullet",
        "Weight":0.02,
        "Usable":false,
        "Price":1,
        "Description":"常用于老式霰弹枪。"
       },
    "45ACP子弹":{
        "ID":13,
        "Type":"Bullet",
        "Weight":0.02,
        "Usable":false,
        "Price":1,
        "Description":"常用于汤姆逊冲锋枪。"
       },
    "绷带":{
        "ID":21,
        "Type":"Medicine",
        "HealValue":10,
        "Weight":0.01,
        "Usable":true,
        "Price":10,
        "Description":"紧急救治医疗物品。可以恢复10点生命。"
       }
   }

var WeaponReference={
    "马桶橛子":{
        "ID":1,
        "Type":"MeleeWeapon",
        "Weight":3,
        "MaxDurability":200,
        "Attack":1,
        "AttackExistTime":0.5,
        "SingleTarget":false,
        "MaxRange":70,
        "KnockBack":150,
        "EnergyNeed":20,
        "GuardingValue":300,
        "DamageAreaRect":Vector2(10,5.5),
        "RigidTime":0.5,
        "ColdTime":2,
        "CenterOffset":Vector2(4,0),
        "DamageAreaOffset":Vector2(7,0.5),
        "Description":"马桶橛子，上古神器。\n攻击力：5\n攻速：中等\n击退力：高"
       },
    "EX咖喱棒":{
        "ID":2,
        "Type":"MeleeWeapon",
        "Weight":10,
        "MaxDurability":200,
        "Attack":20,
        "AttackExistTime":0.1,
        "SingleTarget":true,
        "MaxRange":90,
        "KnockBack":50,
        "EnergyNeed":20,
        "GuardingValue":600,
        "DamageAreaRect":Vector2(13,2),
        "RigidTime":1,
        "ColdTime":3,
        "CenterOffset":Vector2(14,1),
        "DamageAreaOffset":Vector2(21,0.2),
        "Description":"亚瑟王之剑（迫真）。\n攻击力：20\n攻速：较慢\n击退力：较高"
       },
    "军刀":{
        "ID":3,
        "Type":"MeleeWeapon",
        "Weight":1,
        "MaxDurability":300,
        "Attack":5,
        "AttackExistTime":0.1,
        "SingleTarget":true,
        "MaxRange":100,
        "KnockBack":20,
        "EnergyNeed":15,
        "GuardingValue":100,
        "DamageAreaRect":Vector2(12,2.5),
        "RigidTime":0.6,
        "ColdTime":0.5,
        "CenterOffset":Vector2(9.5,0.5),
        "DamageAreaOffset":Vector2(9.5,0.2),
        "Description":"攻击力：5\n攻速：快\n击退力：低"
       },
    "9mm手枪":{
        "ID":11,
        "Type":"RangedWeapon",
        "Weight":2.5,
        "MaxDurability":100,
        "Attack":10,
        "AutoAttack":false,
        "BulletType":"9mm子弹",
        "MagazineCapacity":10,
        "RigidTime":0.6,
        "ColdTime":0.6,
        "ReloadTime":3,
        "RandomAngle":2,
        "MaxRange":600,
        "KnockBack":8,
        "BulletSpeed":15,
        "GuardingValue":1500,
        "Description":"9mm手枪。\n攻击力：10\n使用子弹：9mm子弹\n攻速：一般\n击退力：低",
        "CenterOffset":Vector2(5,0),
        "BulletOffset":Vector2(15,-4)
       },
    "老式霰弹枪":{
        "ID":12,
        "Type":"RangedWeapon",
        "Weight":6,
        "MaxDurability":100,
        "Attack":25,
        "AutoAttack":false,
        "BulletType":"雷明顿16号弹",           
        "MagazineCapacity":6,
        "RigidTime":1.2,
        "ColdTime":1.2,
        "ReloadTime":3.5,
        "RandomAngle":5,
        "MaxRange":350,
        "KnockBack":15,
        "BulletSpeed":15,
        "GuardingValue":1800,
        "Description":"老式霰弹枪\n攻击力：25\n使用子弹：雷明顿16号弹\n攻速：较慢\n击退力：中",
        "CenterOffset":Vector2(9,0),
        "BulletOffset":Vector2(21,-3)   
        },
        "汤姆逊冲锋枪":{
        "ID":13,
        "Type":"RangedWeapon",
        "Weight":5,
        "MaxDurability":500,
        "Attack":5,
        "AutoAttack":true,
        "BulletType":"45ACP子弹",           
        "MagazineCapacity":20,
        "RigidTime":1,
        "ColdTime":0.2,
        "ReloadTime":5,
        "RandomAngle":2,
        "MaxRange":700,
        "KnockBack":5,
        "BulletSpeed":15,
        "GuardingValue":1200,
        "Description":"攻击力：10\n使用子弹：45ACP子弹\n攻速：较快\n击退力：低",
        "CenterOffset":Vector2(7,0),
        "BulletOffset":Vector2(24,-6)   
        }
   }

var EnermyReference={
    "test_enermy":{
        "ID":-1,
        "Type":"Enermy",
        "MaxHealth":100,
        "Attack":10,
        "AttackRange":100,
        "Speed":[3,3,3],
        "CollisionSize":Vector2(25,25),
        "AnimationOffset":Vector2(0,0),
        "Ability":[1,1,1,1],
        "SightAngle":90,
        "SightRange":200,
        "BeforeAttackTime":0.5,
        "AfterAttackTime":0.5,
        "AttackColdTime":2
       }
   }

var HomeUpdateReference={
    "厨房":{
        0:{
            "Need":{"木材":100},
            "Description":"建造厨房。在食物充足的情况下，每天增加20点士气。"
           },
        1:{
            "Need":{"木材":150},
            "Description":"二级厨房。在食物充足的情况下，每天增加30点士气。"
           },
        2:{
            "Need":{"木材":200},
            "Description":"三级厨房。在食物充足的情况下，每天增加40点士气。"
           },
        3:{
            "Need":{"木材":300},
            "Description":"四级厨房。在食物充足的情况下，每天增加50点士气。"
           },
       },
    "储藏室":{
        0:{
            "Need":{"木材":200},
            "Description":"建造仓库。仓库容量由1000kg提升至1500kg。"
           },
        1:{
            "Need":{"木材":400},
            "Description":"二级仓库。仓库容量由1500kg提升至2000kg。"
           },
        2:{
            "Need":{"木材":800},
            "Description":"三级仓库。仓库容量由2000kg提升至2500kg。"
            },
        3:{
            "Need":{"木材":160},
            "Description":"四级仓库。仓库容量由2500kg提升至3000kg。"
            },   
       },
   }

func use_item(Target:Object,ItemName:String):
    if Global.GoodInBackpack.get(ItemName)==null or Global.GoodInBackpack[ItemName]<=0:
        return
    Global.GoodInBackpack[ItemName]-=1
    if ItemRference[ItemName]["Type"]=="Medicine":
        Target.CreatureStatus.heal(ItemRference[ItemName]["HealValue"])
        Global.send_message(Target.Name+"使用了一个"+ItemName+"，恢复了"+String(ItemRference[ItemName]["HealValue"])+"点生命值。")
    Global.update_pause_window()
    

